name: RealShop2
main: fr.crafter.tickleman.realshop2.RealShop2Plugin
version: 2.01
website: http://plugins.crafter.fr/tickleman/RealShop2/
author: tickleman
depend: [Spout]
softdepend: [BOSEconomy, iConomy]
commands:
  mny:
    description: RealEconomy money commands
    permission: mny
    usage: Use /mny help to list available commands
  rshop:
    aliases: rs
    description: RealShop2 chest-shop commands
    permission: realshop2
    usage: Use /rshop help to list available commands
permissions:
  mny:
    description: Gives access to all mny commands
    default: true
  realshop2:
    description: Gives access to all realshop commands
    default: op
  realshop2.display:
    description: Display default shop information
    default: true
  realshop2.shop:
    description: Player can shop
    default: op
