name: RealShop2
main: fr.crafter.tickleman.realshop2.RealShop2Plugin
version: 2.01
website: http://plugins.crafter.fr/tickleman/RealShop2/
authors:
  - tickleman
commands:
  mny:
    description: RealEconomy money commands
  rs:
    description: RealShop2 chest-shop command
  rshop:
    description: RealShop2 chest-shop command
